#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

### Data Structures in python --- 

1. List
2. Tuples
3. Sets
4. Dictionary

In [1]:
!pip install pandas

Requirement already satisfied: pandas in D:\12_2_Weekend\venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in D:\12_2_Weekend\venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\12_2_Weekend\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\12_2_Weekend\venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in D:\12_2_Weekend\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
## Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

data=[1,2,3,4,5]

# series=pd.Series(data)
# print("Series \n",series)
# print(type(series))

series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
mera_index = ['i','ii','iii']
pd.Series(data, index=mera_index)

i      10
ii     20
iii    30
dtype: int64

In [7]:
## Dataframe
## create a Dataframe from a dictionary of list

data={
    'Name':['Abhishek','John','Jack'], 
    'Age':[32,30,45], 
    'City':['Bangalore','New York','Florida']
    }
df=pd.DataFrame(data)

print(type(df))

# print(df)
df

<class 'pandas.DataFrame'>

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   30   New York
2      Jack   45    Florida

In [21]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Abhishek','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':"Florida"},
    {'Name':'Bappy','Age':32,'City':"Florida"},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)

print(type(df))
df

<class 'pandas.DataFrame'>

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   34    Florida
2     Bappy   32    Florida
3      JAck   32  Bangalore

In [10]:
import sys

print(sys.getsizeof(df))

313

In [11]:
import pandas as pd

In [16]:
df=pd.read_csv('sales_data.csv')
# .head() -- by default it will show top 5 rows inside your dataset... Also u can give any number and it will show you that much of data.
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [13]:
df_1 = pd.read_excel("sales_data.xlsx")

df_1

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
df.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [18]:
# .describe() -- It will show you stats of numeric columns
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    str
 2   Product Category  240 non-null    str
 3   Product Name      240 non-null    str
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    str
 8   Payment Method    240 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 32.0 KB

In [ ]:
df.tail(10)

In [22]:
### Accessing Data From Dataframe
df

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   34    Florida
2     Bappy   32    Florida
3      JAck   32  Bangalore

In [23]:
df['Name']

0    Abhishek
1        John
2       Bappy
3        JAck
Name: Name, dtype: str

In [24]:
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                               'Mahindra', 'Maruti', 'Hyundai',
                               'Renault', 'Tata', 'Maruti'],
                     'Year': [2012, 2014, 2011, 2015, 2012,
                              2016, 2014, 2018, 2019],
                     'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                     'City': ['Gurgaon', 'Delhi', 'Mumbai',
                              'Delhi', 'Mumbai', 'Delhi',
                              'Mumbai', 'Chennai',  'Ghaziabad'],
                     'Mileage':  [28, 27, 25, 26, 28,
                                  29, 24, 21, 24]})

# displaying the DataFrame
display(data)

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

🛠️ Key Comparison
## Feature 	.loc	.iloc
1. Selection Type	Label-based (uses names)	Integer-based (uses positions)
2. Slicing Endpoint	Included (inclusive)	Excluded (exclusive)
3. Allowed Inputs	Strings, lists of labels, boolean arrays	Integers, lists of integers, slices
4. Out-of-bounds	Raises KeyError	Raises IndexError
5. Boolean Masking	Supported directly	Often requires list conversion

In [25]:
display(data.loc[(data.Brand == 'Maruti') & (data.Mileage > 25)])

    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [26]:
display(data.iloc[[0, 2, 4, 7]])

    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
2    Tata  2011       60000   Mumbai       25
4  Maruti  2012       10000   Mumbai       28
7    Tata  2018       15000  Chennai       21

In [ ]:
df.loc[0]

In [ ]:
df.iloc[0]

In [27]:
df

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   34    Florida
2     Bappy   32    Florida
3      JAck   32  Bangalore

In [28]:
## Accessing a specified element
df.at[2,'Age']

np.int64(32)

In [29]:
df.at[2,'Name']

'Bappy'

In [30]:
## Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [ ]:
df

In [31]:
### Data MAnipulation with Dataframe
df

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   34    Florida
2     Bappy   32    Florida
3      JAck   32  Bangalore

In [33]:
## Adding a column
df['Salary']=[2500,50000,60000,70000]
df

       Name  Age       City  Salary
0  Abhishek   32  Bangalore    2500
1      John   34    Florida   50000
2     Bappy   32    Florida   60000
3      JAck   32  Bangalore   70000

In [34]:
df

       Name  Age       City  Salary
0  Abhishek   32  Bangalore    2500
1      John   34    Florida   50000
2     Bappy   32    Florida   60000
3      JAck   32  Bangalore   70000

In [38]:
## Remove a column
df.drop('Salary',axis=1, inplace=True)

In [39]:
df

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   34    Florida
2     Bappy   32    Florida
3      JAck   32  Bangalore

In [40]:
## Add age to the column
df['Age']=df['Age']+1
df

       Name  Age       City
0  Abhishek   33  Bangalore
1      John   35    Florida
2     Bappy   33    Florida
3      JAck   33  Bangalore

In [41]:
df.drop(0,inplace=True)

In [42]:
df

    Name  Age       City
1   John   35    Florida
2  Bappy   33    Florida
3   JAck   33  Bangalore

In [ ]:
df=pd.read_csv('sales_data.csv')
df.head(5)

In [ ]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n")
df.describe()

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [43]:
import pandas as pd
df = pd.read_json("C:/Users/Admin/Downloads/MOCK_DATA (1).json")

df

,id,first_name,last_name,email,gender,Mobile_Number
0,1,Lamont,Woollhead,lwoollhead0@ocn.ne.jp,Male,+94 (794) 652-6239
1,2,Valentijn,Ramsdale,vramsdale1@dot.gov,Male,+62 (679) 380-5174
2,3,Nolan,Jeppe,njeppe2@examiner.com,Agender,+92 (251) 497-2814
3,4,Reeva,Guilford,rguilford3@nytimes.com,Bigender,+30 (731) 960-9543
4,5,Artair,Ogilvy,aogilvy4@ask.com,Male,+86 (763) 271-7308
...,...,...,...,...,...,...
995,996,Alexa,Brealey,abrealeyrn@surveymonkey.com,Female,+66 (169) 709-2166
996,997,Mona,Cromb,mcrombro@tamu.edu,Female,+46 (127) 230-8238
997,998,Rochella,Barrasse,rbarrasserp@webs.com,Female,+503 (964) 901-9065
998,999,Kylynn,Pellant,kpellantrq@earthlink.net,Female,+86 (435) 772-0471
999,1000,Brewster,Zimmerman,bzimmermanrr@biglobe.ne.jp,Male,+996 (157) 110-4786